image: node:20-alpine

variables:
  PNPM_CACHE_DIR: .pnpm-store
  DOCKER_IMAGE_BACKEND: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG
  DOCKER_IMAGE_FRONTEND: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store
    - node_modules/

stages:
  - install
  - lint
  - build_docker
  - deploy

install_dependencies:
  stage: install
  image: node:20-slim
  script:
    - corepack enable
    - pnpm install --no-frozen-lockfile
  artifacts:
    paths:
      - node_modules/

linting:
  stage: lint
  image: node:20-slim
  script:
    - corepack enable
    - pnpm lint
  dependencies:
    - install_dependencies

build_images:
  stage: build_docker
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --target backend -t $DOCKER_IMAGE_BACKEND .
    - docker build --target frontend -t $DOCKER_IMAGE_FRONTEND .
    - docker push $DOCKER_IMAGE_BACKEND
    - docker push $DOCKER_IMAGE_FRONTEND
  only:
    - dev
    - main

deploy_to_server:
  stage: deploy
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Use the images we just pushed to the registry
    - docker pull $DOCKER_IMAGE_BACKEND
    - docker pull $DOCKER_IMAGE_FRONTEND
    # Stop the old ones and start the new ones
    - docker compose down --remove-orphans || true
    - docker compose up -d
  only:
    - dev


